#!/usr/sbin/nft -f

flush ruleset

table inet agent_s_filter {
    chain output {
        type filter hook output priority 0; policy accept;

        oifname "lo" accept
        ct state established,related accept
        ip daddr 10.0.2.3 udp dport 53 accept
        ip daddr 10.0.2.3 tcp dport 53 accept
        ip daddr 10.0.0.0/8 reject
        ip daddr 100.64.0.0/10 reject
        ip daddr 169.254.0.0/16 reject
        ip daddr 172.16.0.0/12 reject
        ip daddr 192.168.0.0/16 reject
    }
}
